<a href="https://colab.research.google.com/github/prempanchal20/Data_Analyst_Practise/blob/develop/Numpy_Pracitse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy Practise**


In [ ]:
import numpy as np

**2D Array**

In [ ]:
myArr = np.array([[3,4,8,6,7]], np.int8)
myArr

array([[3, 4, 8, 6, 7]], dtype=int8)

**Indexing**

In [ ]:
myArr[0]

array([3, 4, 8, 6, 7], dtype=int8)

In [ ]:
myArr.shape

(1, 5)

In [ ]:
myArr.dtype

dtype('int8')

**Array Creation: Conversion From other Python Structures**

In [ ]:
listArray = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])

listArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
listArray.dtype

dtype('int64')

In [ ]:
listArray.shape

(3, 3)

In [ ]:
listArray[0]

array([1, 2, 3])

**Slicing**

In [ ]:
arr2 = listArray[1:2]
arr2

array([[4, 5, 6]])

In [ ]:
np.array({12,23,34,23,34})

array({34, 12, 23}, dtype=object)

**Linspace used to create an evenly spaced sequence in a specified interval**

numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

In [ ]:
lspace = np.linspace(1,50,num=50, endpoint=True)
lspace

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [ ]:
lspace,step_size= np.linspace(1,5,num=3,retstep=True)
lspace

array([1., 3., 5.])

In [ ]:
step_size

2.0

**Difference between empty and random**

In [ ]:
emp = np.empty([4,6])
emp

array([[0.57585591, 0.97273841, 0.31843687, 0.15441845, 0.77283738,
        0.58273414],
       [0.85524494, 0.82048971, 0.67479602, 0.12864207, 0.2372585 ,
        0.01721193],
       [0.4310911 , 0.99150351, 0.66336653, 0.31893803, 0.79580264,
        0.07057384],
       [0.1093517 , 0.92589929, 0.29453874, 0.31969987, 0.71777346,
        0.67129687]])

In [ ]:
random_array = np.random.rand(4,6)
random_array

array([[0.78922562, 0.21426148, 0.87209415, 0.8841258 , 0.04375909,
        0.92695658],
       [0.22049081, 0.46702988, 0.11201155, 0.06924249, 0.05162659,
        0.28088316],
       [0.04526658, 0.7585499 , 0.57362433, 0.09355723, 0.91770849,
        0.31644013],
       [0.6934033 , 0.10641131, 0.63287821, 0.78286562, 0.69502596,
        0.96427134]])

**Generate Only 3 random numbers between 1 to 10**

In [ ]:
random_array = np.random.randint(1, 10, 3)
random_array

array([9, 9, 6])

**Indexing in 2D Array**

In [ ]:
arr1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

type(arr1)

numpy.ndarray

In [ ]:
arr1[:,2]

array([3, 6, 9])

In [ ]:
arr1[1:,1:]

array([[5, 6],
       [8, 9]])